[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "sh ./entrypoint.sh"
healthcheckPath = "/health/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.env]
DEBUG = "False"
ALLOWED_HOSTS = "*.railway.app"
CSRF_TRUSTED_ORIGINS = "https://*.railway.app"
DB_INIT_PASSWORD = "d3f6a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d"
TIME_ZONE = "UTC" 