[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "sh ./entrypoint.sh"
healthcheckPath = "/health/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.env]
DEBUG = "False"
ALLOWED_HOSTS = "*.railway.app"
CSRF_TRUSTED_ORIGINS = "https://*.railway.app" 