[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "sh ./entrypoint.sh"
healthcheckPath = "/health/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
startupTimeout = 300

[deploy.env]
DEBUG = "False"
ALLOWED_HOSTS = "powerful-quietude-production.up.railway.app,*.railway.app"
CSRF_TRUSTED_ORIGINS = "https://powerful-quietude-production.up.railway.app,https://*.railway.app"
SECRET_KEY = "${SECRET_KEY}"
DB_INIT_PASSWORD = "d3f6a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d"
TIME_ZONE = "UTC"

# PostgreSQL environment variables (these will be set by Railway)
POSTGRES_DB = "${POSTGRES_DB}"
POSTGRES_USER = "${POSTGRES_USER}"
POSTGRES_PASSWORD = "${POSTGRES_PASSWORD}"
POSTGRES_PORT = "${PGPORT}"
DATABASE_URL = "${DATABASE_URL}"

# PostgreSQL initialization
[postgres]
initScript = "init.sql"

# Wait for database to be ready
[deploy.dependencies]
postgresql = true 